# Use uma imagem base com suporte a C++ e PThreads
FROM gcc:latest

# Cria um diretório para o código
WORKDIR /app

# Copia o código para o container
COPY 8threads.cpp .

# Compila o código com suporte a PThreads
RUN g++ 8threads.cpp -o 8threads -pthread

# Comando para executar o código
CMD ["./8threads"]
